# -*- coding: utf-8 -*-
"""LAb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1leudE7zfskb0bWDVFCm7b3PmlPQN5mW2
"""

from google.colab import files
import cv2
from google.colab.patches import cv2_imshow

uploaded = files.upload()
filename = list(uploaded.keys())[0]

img = cv2.imread(filename)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

cv2_imshow(img)
cv2_imshow(gray)

from google.colab import files
import cv2
from google.colab.patches import cv2_imshow

uploaded = files.upload()
filename = list(uploaded.keys())[0]

img = cv2.imread(filename)

# Apply Gaussian Blur
blur = cv2.GaussianBlur(img, (5,5), 0)

cv2_imshow(img)
cv2_imshow(blur)

from google.colab import files
import cv2
from google.colab.patches import cv2_imshow

uploaded = files.upload()
filename = list(uploaded.keys())[0]

img = cv2.imread(filename)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Apply Canny Edge Detection (Outline)
edges = cv2.Canny(gray, 100, 200)

cv2_imshow(img)
cv2_imshow(edges)

from google.colab import files
import cv2
import numpy as np
from google.colab.patches import cv2_imshow

uploaded = files.upload()
filename = list(uploaded.keys())[0]

img = cv2.imread(filename)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Create kernel
kernel = np.ones((5,5), np.uint8)

# Apply Dilation
dilated = cv2.dilate(gray, kernel, iterations=1)

cv2_imshow(img)
cv2_imshow(dilated)

from google.colab import files
import cv2
import numpy as np
from google.colab.patches import cv2_imshow

uploaded = files.upload()
filename = list(uploaded.keys())[0]

img = cv2.imread(filename)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

kernel = np.ones((5,5), np.uint8)

eroded = cv2.erode(gray, kernel, iterations=1)

cv2_imshow(img)
cv2_imshow(eroded)

import cv2
import time

# Capture video from webcam
cap = cv2.VideoCapture(0)

if not cap.isOpened():
    print("Error opening video stream")
else:
    while True:
        ret, frame = cap.read()
        if not ret:
            break

        # Normal Speed
        cv2.imshow("Normal Video", frame)

        # Slow Motion (Delay Increased)
        cv2.imshow("Slow Motion", frame)
        cv2.waitKey(100)   # 100 ms delay (slow)

        # Fast Motion (Frame Skipping)
        for i in range(5):   # Skip 5 frames
            cap.read()

        cv2.imshow("Fast Motion", frame)

        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

cap.release()
cv2.destroyAllWindows()

from google.colab import files
import cv2
from google.colab.patches import cv2_imshow

uploaded = files.upload()
filename = list(uploaded.keys())[0]

img = cv2.imread(filename)

# Scale to Smaller Size (50%)
smaller = cv2.resize(img, None, fx=0.5, fy=0.5)

# Scale to Bigger Size (150%)
bigger = cv2.resize(img, None, fx=1.5, fy=1.5)

cv2_imshow(img)
cv2_imshow(smaller)
cv2_imshow(bigger)

from google.colab import files
import cv2
from google.colab.patches import cv2_imshow

uploaded = files.upload()
filename = list(uploaded.keys())[0]

img = cv2.imread(filename)

rotate_cw = cv2.rotate(img, cv2.ROTATE_90_CLOCKWISE)

rotate_ccw = cv2.rotate(img, cv2.ROTATE_90_COUNTERCLOCKWISE)

cv2_imshow(img)
cv2_imshow(rotate_cw)
cv2_imshow(rotate_ccw)

from google.colab import files
import cv2
import numpy as np
from google.colab.patches import cv2_imshow

uploaded = files.upload()
filename = list(uploaded.keys())[0]

img = cv2.imread(filename)

# Create Translation Matrix
M = np.float32([[1, 0, 100],
                [0, 1, 50]])

# Apply Translation
moved = cv2.warpAffine(img, M, (img.shape[1], img.shape[0]))

cv2_imshow(img)
cv2_imshow(moved)

from google.colab import files
import cv2
import numpy as np
from google.colab.patches import cv2_imshow

uploaded = files.upload()
filename = list(uploaded.keys())[0]

img = cv2.imread(filename)

rows, cols = img.shape[:2]

# Define 3 points from original image
pts1 = np.float32([[50, 50],
                   [200, 50],
                   [50, 200]])

# Define new positions of those 3 points
pts2 = np.float32([[10, 100],
                   [200, 50],
                   [100, 250]])

# Get Affine transformation matrix
M = cv2.getAffineTransform(pts1, pts2)

# Apply Affine transformation
affine = cv2.warpAffine(img, M, (cols, rows))

cv2_imshow(img)
cv2_imshow(affine)

from google.colab import files
import cv2
import numpy as np
from google.colab.patches import cv2_imshow

uploaded = files.upload()
filename = list(uploaded.keys())[0]

img = cv2.imread(filename)

rows, cols = img.shape[:2]

# Select 4 points from original image
pts1 = np.float32([[50, 50],
                   [300, 50],
                   [50, 300],
                   [300, 300]])

# Define new positions for those 4 points
pts2 = np.float32([[0, 0],
                   [cols, 0],
                   [0, rows],
                   [cols, rows]])

# Get Perspective Transformation matrix
M = cv2.getPerspectiveTransform(pts1, pts2)

# Apply Perspective Transformation
perspective = cv2.warpPerspective(img, M, (cols, rows))

cv2_imshow(img)
cv2_imshow(perspective)

import cv2
import numpy as np

cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()
    if not ret:
        break

    rows, cols = frame.shape[:2]

    # Select 4 points from original frame
    pts1 = np.float32([[50, 50],
                       [300, 50],
                       [50, 300],
                       [300, 300]])

    # Define new positions
    pts2 = np.float32([[0, 0],
                       [cols, 0],
                       [0, rows],
                       [cols, rows]])

    # Get Perspective matrix
    M = cv2.getPerspectiveTransform(pts1, pts2)

    # Apply transformation
    perspective = cv2.warpPerspective(frame, M, (cols, rows))

    cv2.imshow("Original Video", frame)
    cv2.imshow("Perspective Video", perspective)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()